### ISSUE TITLE
请给出转换后的onnx模型

### ISSUE THREAD

**Issue by vkl-git** [fabio-sim/LightGlue-ONNX#10]
您好，方便提供转换后的两个onnx模型的下载链接吗？

**Comment by fabio-sim** [comment]
您好 @vkl-git ，感谢您的兴趣。

全部DISK，SuperPoint，和LightGlue的ONNX模型已经在[v0.1.0](https://github.com/fabio-sim/LightGlue-ONNX/releases/tag/v0.1.0)中发布。请随意选择
