### ISSUE TITLE
onnxruntime error

### ISSUE THREAD

**Issue by valenbase** [fabio-sim/LightGlue-ONNX#21]
use the command to export the end2end model
`python export.py \                                                                                                       
  --img_size 512  \
  --extractor_type disk \
  --lightglue_path weights/superpoint_lightglue.onnx \
  --end2end \
  --safe`
and then load \ build and export the onnx model to another embedded platform
then the error message occurs
_[ONNXRuntimeError] : 1 : FAIL : Node (/extractor/unet/2/Concat) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=257 Target=256 Dimension=2_

**Comment by fabio-sim** [comment]
Hi @valenbase , I've provided an exported end2end model in your previous issue (https://github.com/fabio-sim/LightGlue-ONNX/issues/19#issuecomment-1651650399). Could you try using that one?

I recommend exporting with `python export.py --extractor_type disk --dynamic --end2end`. If you provide only one number in `--img_size` without specifying `--dynamic`, the images used for tracing ([image0](https://github.com/fabio-sim/LightGlue-ONNX/blob/main/assets/sacre_coeur1.jpg) and [image1](https://github.com/fabio-sim/LightGlue-ONNX/blob/main/assets/sacre_coeur2.jpg)) will be resized such that their longer side is equal to `--img_size`, and the exported model will be locked into whatever those input shapes are.
