### ISSUE TITLE
Input Tensor /Gather_3_output_0 is unused 

### ISSUE THREAD

**Issue by goktugyildirim4d** [fabio-sim/LightGlue-ONNX#22]
Thanks for your job. I'm getting this warning sometimes. What is the reason for this?

`2023-07-27 12:19:17.191206340 [W:onnxruntime:Default, tensorrt_execution_provider.h:75 log] [2023-07-27 09:19:17 WARNING] [RemoveDeadLayers] Input Tensor /Gather_3_output_0 is unused or used only at compile-time, but is not being removed.`

**Comment by fabio-sim** [comment]
Hi @goktugyildirim4d , thank you for your interest in LightGlue-ONNX.

Regarding that warning, I'm not all too sure either. It may have something to do with ORT's optimizations, but as long as the outputs are correct, this warning shouldn't be a problem.
