### ISSUE TITLE
License issue of superpoint + LightGlue onnx

### ISSUE THREAD

**Issue by QuanNguyen94** [fabio-sim/LightGlue-ONNX#24]
Hi, your work is really great and helpful. Thank for your effort to maintain this repo. I wonder if Superpoint+LightGlue onnx have any issues of license for commercial use ?

**Comment by fabio-sim** [comment]
Hi @QuanNguyen94 , thank you for your interest in LightGlue-ONNX!

This fork inherits the original repository's license (Apache License, Version 2.0).

**Comment by QuanNguyen94** [comment]
Is it not infringe copyright of Superpoint of MagicLeap ? https://github.com/magicleap/SuperPointPretrainedNetwork/blob/master/LICENSE

**Comment by fabio-sim** [comment]
You could try opening an issue in the original LightGlue repository. I'm not a legal expert.
