### ISSUE TITLE
the model which set depth_confidence && width_confidence can't run by infer.py.

### ISSUE THREAD

**Issue by demonove** [fabio-sim/LightGlue-ONNX#27]
In export.py, I use:    lightglue = LightGlue(extractor_type, flash=flash, depth_confidence=0.95, width_confidence=0.99).eval()    to build .onnx
when I use this .onnx in infer.py, it can't run normally.

E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Squeeze node. Name:'/Squeeze_3' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:52 static onnxruntime::TensorShapeVector onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const TensorShapeVector&) input_shape[i] == 1 was false. Dimension of input 1 must be 1 instead of 2. shape={2045,2}

Whether can I set depth_confidence && width_confidence in export.py???
Or the onnxruntime I used is something wrong?

**Comment by fabio-sim** [comment]
Hi @demonove , thank you for your interest in LightGlue-ONNX.

The depth/width confidence parameters induce dynamic/data-dependent control flow in LightGlue (a for-loop with a variable number of iterations which depend on the input itself). The current tracing-based `torch.onnx.export()` [cannot capture this adaptive behaviour](https://github.com/fabio-sim/LightGlue-ONNX#lightglue-keypoint-matching), where _'easier'_ images only have to go through fewer layers (e.g., L=3-4), while _'harder'_ images need to pass through more layers (e.g., L=7-9).

I hope the upcoming [`torch.export()` path](https://youtu.be/kJiv1DPK8_U) supports this use case though.
