### ISSUE TITLE
How to export FP32 model?

### ISSUE THREAD

**Issue by JingruiYu** [fabio-sim/LightGlue-ONNX#35]
EVALUATION.md shows the latency of FP32. With export.py and optimize.py only the FP16 model is available. So how to export FP32 model? And could you give the accuracy of different models? thanks!

**Comment by fabio-sim** [comment]
Hi @JingruiYu, thank you for your interest in LightGlue-ONNX.

If you run `optimize.py` as follows:
```bash
python optimize.py --input weights/superpoint_lightglue.onnx
```
It should produce two outputs:
- `weights/superpoint_lightglue_fused.onnx`: This is the FP32 one
- `weights/superpoint_lightglue_fused_fp16.onnx`: This is the FP16 one

At the moment, I don't have any plans to calculate the accuracies (busy with other stuff). But you're very welcome to contribute these results!

**Comment by JingruiYu** [comment]
Thanks!
