### ISSUE TITLE
What's the difference between the relased models?

### ISSUE THREAD

**Issue by JingruiYu** [fabio-sim/LightGlue-ONNX#37]
There are many models under [relase_v0.1.3](https://github.com/fabio-sim/LightGlue-ONNX/releases), what is the difference between them?
I thought the 512 in the name refers to the image resolution. But when I use v0.1.3 code to export 512 models via command 
`python export.py --img_size 512 --extractor_type superpoint --lightglue_path weights/superpoint_lightglue_512_end2end_my.onnx --dynamic --end2end`. 
The performance of the exported onnx model is different from the relased _superpoint_512_lightglue_end2end.onnx_.
I didn't find optimize.py so I assume it has nothing to do with model optimization? But then it's not clear what causes the different models obtained and what makes these models different? Thanks!

**Comment by fabio-sim** [comment]
Hi @JingruiYu

The numbers in the name (512, 1024, 2048) correspond to the `--max_num_keypoints` argument, not `--img_size`. The models under v0.1.3 take any input resolution as they were exported with `--dynamic`.
