### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by czy-1234** [fabio-sim/LightGlue-ONNX#38]
I'm getting an error during running the infer.py:ValueError: too many values to unpack (expected 2)
This error occurs at line 53 of onnx_runner/lightglue.py。Can you help me with the answer

**Comment by fabio-sim** [comment]
Hi @czy-1234, thank you for your interest in LightGlue-ONNX.

It seems that you are using a model version `<1.0.0`, but your version of `infer.py` is `>=1.0.0`. Please checkout the corresponding [release tag](https://github.com/fabio-sim/LightGlue-ONNX/tags).
