### ISSUE TITLE
Failed to test the end-to-end onnx model by trtexec

### ISSUE THREAD

**Issue by BoyceL** [fabio-sim/LightGlue-ONNX#43]
Hi @fabio-sim Im trying to test and convert the superpoint_lightglue_end2end_fused.onnx model into tensorrt engine with TensorRT-8.6.1.6, but it turns out that the operater `MultiHeadAttention` has not been registered. I have tried the [tenssort oss](https://github.com/NVIDIA/TensorRT) but it didn't help. Could you help me solve this problem or provide a reasonable solution to covert it into engine? 
```
[10/27/2023-09:38:30] [I] [TRT] No importer registered for op: MultiHeadAttention. Attempting to import as plugin.
[10/27/2023-09:38:30] [I] [TRT] Searching for plugin: MultiHeadAttention, plugin_version: 1, plugin_namespace: 
[10/27/2023-09:38:30] [E] [TRT] 3: getPluginCreator could not find plugin: MultiHeadAttention version: 1
[10/27/2023-09:38:30] [E] [TRT] parsers/onnx/ModelImporter.cpp:768: While parsing node number 509 [MultiHeadAttention -> "/lightglue/transformers.0/self_attn/Reshape_5_output_0"]:
[10/27/2023-09:38:30] [E] [TRT] parsers/onnx/ModelImporter.cpp:769: --- Begin node ---
[10/27/2023-09:38:30] [E] [TRT] parsers/onnx/ModelImporter.cpp:770: input: "Transpose_0_out"
output: "/lightglue/transformers.0/self_attn/Reshape_5_output_0"
name: "MultiHeadAttention_0"
op_type: "MultiHeadAttention"
attribute {
  name: "num_heads"
  i: 4
  type: INT
}
domain: "com.microsoft"

[10/27/2023-09:38:30] [E] [TRT] parsers/onnx/ModelImporter.cpp:771: --- End node ---
[10/27/2023-09:38:30] [E] [TRT] parsers/onnx/ModelImporter.cpp:773: ERROR: parsers/onnx/builtin_op_importers.cpp:5405 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[10/27/2023-09:38:30] [E] Failed to parse onnx file
[10/27/2023-09:38:30] [I] Finished parsing network model. Parse time: 0.0809233
[10/27/2023-09:38:30] [E] Parsing model failed
[10/27/2023-09:38:30] [E] Failed to create engine from model or file.
[10/27/2023-09:38:30] [E] Engine set up failed
```

**Comment by Albert337** [comment]
hey, i  try to use trtexec to convert superpoint_lightglue.onnx to .trt file,it showed success. but when i try to test .trt , it occured the error
![image](https://github.com/fabio-sim/LightGlue-ONNX/assets/33714840/2486d4a0-a0d3-4c0d-80af-02ca338cc061)
i thought the error occurred during using trtexec.

**Comment by BoyceL** [comment]
> hey, i try to use trtexec to convert superpoint_lightglue.onnx to .trt file,it showed success. but when i try to test .trt , it occured the error ![image](https://user-images.githubusercontent.com/33714840/278978889-2486d4a0-a0d3-4c0d-80af-02ca338cc061.png) i thought the error occurred during using trtexec.

Yes. It seems that the `superpoint_lightglue.onnx` could pass the test, but after the optimization by `optimize.py`, turning it 
 into `superpoint_lightglue_fused.onnx` , some layers in the network has been summed up to a MultiHeadAttention layer, which is not supported in tensorrt now.

About your error here, I think that try to follow the error message to use `set_input_shape` instead of `set_binding_shape` may be useful?

**Comment by Albert337** [comment]
> > hey, i try to use trtexec to convert superpoint_lightglue.onnx to .trt file,it showed success. but when i try to test .trt , it occured the error ![image](https://user-images.githubusercontent.com/33714840/278978889-2486d4a0-a0d3-4c0d-80af-02ca338cc061.png) i thought the error occurred during using trtexec.
> 
> Yes. It seems that the `superpoint_lightglue.onnx` could pass the test, but after the optimization by `optimize.py`, turning it into `superpoint_lightglue_fused.onnx` , some layers in the network has been summed up to a MultiHeadAttention layer, which is not supported in tensorrt now.
> 
> About your error here, I think that try to follow the error message to use `set_input_shape` instead of `set_binding_shape` may be useful?

yes ,thanks, i use set_binding_shape to set the input shape, but it does not work when it is the output turn.
`        inputs = [kpts0,kpts1,desc0,desc1]  
        self.bufferH = []
        self.bufferD = []

        output_shape = [(num_matches,2), (num_matches,)]

        ####binding outputshape
        # output_matches_binding_idx = self.engine.get_binding_index("matches0")
        # output_scores_binding_idx = self.engine.get_binding_index("mscores0")
        # self.context.set_binding_shape(output_matches_binding_idx,tuple(output_shape[0]))
        # self.context.set_binding_shape(output_scores_binding_idx,tuple(output_shape[1]))

        for i in range(self.nInput):
            self.bufferH.append(np.ascontiguousarray(inputs[i]))  
            self.context.set_binding_shape(i, tuple(inputs[i].shape))`

**Comment by fabio-sim** [comment]
Hi @BoyceL @Albert337, thank you for your interest in LightGlue-ONNX.

I haven't had a chance to look at using `trtexec` yet. I'll check it out in the coming weeks.

**Comment by BoyceL** [comment]
> Hi @BoyceL @Albert337, thank you for your interest in LightGlue-ONNX.
> 
> I haven't had a chance to look at using `trtexec` yet. I'll check it out in the coming weeks.

Thanks. Take your time.

**Comment by BoyceL** [comment]
> > > hey, i try to use trtexec to convert superpoint_lightglue.onnx to .trt file,it showed success. but when i try to test .trt , it occured the error ![image](https://user-images.githubusercontent.com/33714840/278978889-2486d4a0-a0d3-4c0d-80af-02ca338cc061.png) i thought the error occurred during using trtexec.
> > 
> > 
> > Yes. It seems that the `superpoint_lightglue.onnx` could pass the test, but after the optimization by `optimize.py`, turning it into `superpoint_lightglue_fused.onnx` , some layers in the network has been summed up to a MultiHeadAttention layer, which is not supported in tensorrt now.
> > About your error here, I think that try to follow the error message to use `set_input_shape` instead of `set_binding_shape` may be useful?
> 
> yes ,thanks, i use set_binding_shape to set the input shape, but it does not work when it is the output turn. ` inputs = [kpts0,kpts1,desc0,desc1] self.bufferH = [] self.bufferD = []
> 
> ```
>     output_shape = [(num_matches,2), (num_matches,)]
> 
>     ####binding outputshape
>     # output_matches_binding_idx = self.engine.get_binding_index("matches0")
>     # output_scores_binding_idx = self.engine.get_binding_index("mscores0")
>     # self.context.set_binding_shape(output_matches_binding_idx,tuple(output_shape[0]))
>     # self.context.set_binding_shape(output_scores_binding_idx,tuple(output_shape[1]))
> 
>     for i in range(self.nInput):
>         self.bufferH.append(np.ascontiguousarray(inputs[i]))  
>         self.context.set_binding_shape(i, tuple(inputs[i].shape))`
> ```

Sorry that I have no clue about your error here, I'm just a learner in a few weeks :(

**Comment by fabio-sim** [comment]
Hi, I've added the TRT engine-convertible ONNX model [here](https://github.com/fabio-sim/LightGlue-ONNX/releases/download/v1.0.0/superpoint_lightglue.trt.onnx). You can also refer to https://github.com/fabio-sim/LightGlue-ONNX/issues/56 and this script:
https://github.com/fabio-sim/LightGlue-ONNX/blob/bcf96b76f9d838bc1240da79442001df97be341f/trt_infer.py#L1-L122
