### ISSUE TITLE
support dynamic batch size

### ISSUE THREAD

**Issue by WalkerWen** [fabio-sim/LightGlue-ONNX#54]
Hi, If light glue onnx support dynamic batch size now?
like :
dynamic_axes={
                "kpts0": {0: "batch_size", 1: "num_keypoints0"},
                "kpts1": {0: "batch_size", 1: "num_keypoints1"},
                "desc0": {0: "batch_size", 1: "num_keypoints0"},
                "desc1": {0: "batch_size", 1: "num_keypoints1"},
}

**Comment by fabio-sim** [comment]
Hi @WalkerWen, thank you for your interest in LightGlue-ONNX.

Batch size > 1 is not supported.
