### ISSUE TITLE
aliked

### ISSUE THREAD

**Issue by sushi31415926** [fabio-sim/LightGlue-ONNX#55]
there is a plan to add aliked support?

**Comment by fabio-sim** [comment]
Hi @sushi31415926, thank you for your interest in LightGlue-ONNX.

Not at the moment. [ALIKED](https://github.com/cvg/glue-factory/blob/main/gluefactory/models/extractors/aliked.py) seems to use some difficult operators like deformable convolution, so I'm not sure if it can be exported to ONNX correctly.

**Comment by 1191658517** [comment]
I tried it but it rasie :torch.onnx.errors.UnsupportedOperatorError: ONNX export failed on an operator with unrecognized namespace torchvision::deform_conv2d. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
aliked cant be exported to ONNX correctly.
