### ISSUE TITLE
Internal Error (/lightglue/ArgMax)

### ISSUE THREAD

**Issue by chenscottus** [fabio-sim/LightGlue-ONNX#66]
When I run the model with TensorRT 8.6.2 and CUDA 12.2 in Jetson Device, there are a lot of errors:
            (Ubuntu 22.04, Jack Pack 6.0 R36.2 https://developer.nvidia.com/embedded/jetpack#collapseAllJetson )

          [E] [TRT] 7: [shapeMachine.cpp::nvinfer1::rt::ShapeMachineRoutine::executeContinuation::864] Error Code 7: Internal Error (/lightglue/ArgMax: length of reduction axis ((MIN 2048 (# 0 (VALUE /extractor_1/NonZero_1[size])))) is smaller than K (1) Condition '==' violated: 0 != 1. Instruction: CHECK_EQUAL 0 1.)

There is no such issue when I run the model with TensorRT 8.6.1.6 in Windows.

Thanks!

-Scott

**Comment by chenscottus** [comment]
The model is 
    https://github.com/fabio-sim/LightGlue-ONNX/releases/download/v0.1.3/superpoint_2048_lightglue_end2end.onnx 
   from
   https://github.com/fabio-sim/LightGlue-ONNX/releases/tag/v0.1.3

**Comment by chenscottus** [comment]
/usr/bin/trtexec  --workspace=40960  --onnx=/home/dev/projects/models/superpoint_2048_lightglue_end2end_tensorrt_sim.onnx  --saveEngine=/home/dev/projects/models/superpoint_2048_lightglue_end2end_tensorrt_sim_1x1x3840x640_1x1x3840x128.fp32.trt8.v8.6.2.3.sm87.engine --minShapes=image0:1x1x3840x640,image1:1x1x3840x128 --optShapes=image0:1x1x3840x640,image1:1x1x3840x128 --maxShapes=image0:1x1x3840x640,image1:1x1x3840x128

**Comment by chenscottus** [comment]
https://github.com/NVIDIA/TensorRT/issues/3690

**Comment by fabio-sim** [comment]
Hi @chenscottus, thank you for your interest in LightGlue-ONNX.

Sorry, I don't have any Jetson devices so I can't try to reproduce this.
