### ISSUE TITLE
".trt.onnx"export example 

### ISSUE THREAD

**Issue by WYKXD** [fabio-sim/LightGlue-ONNX#70]
Hello, "superpoint_lightglue.trt.onnx"

Is there an export example of the file? I see examples of "_fp16.onnx" and "_fused.onnx" in the code, but I don't see examples of trt.onnx

**Comment by fabio-sim** [comment]
Hi @WYKXD, thank you for your interest in LightGlue-ONNX.

The `.trt.onnx` refers to the ONNX model that has undergone shape inference and can therefore be consumed by TensorRT. You can use the following command:

```python
python -m onnxruntime.tools.symbolic_shape_infer --auto_merge --input superpoint_lightglue.onnx --output superpoint_lightglue.trt.onnx
```

Hope this helps :)
