### ISSUE TITLE
how to convert onnx into an rknn model？

### ISSUE THREAD

**Issue by ouxiand** [fabio-sim/LightGlue-ONNX#72]
Hello,  Thank you for sharing such a great project!

May I ask how to convert onnx into an rknn model？I want to run this lightglue onnx model on rknn npu.

However, rknn does not support dynamic calls and has no idea at all.

Who knows how to solve it?

**Comment by caiya55** [comment]
you can set the shape of the model to static shape

**Comment by ouxiand** [comment]
Input/Output has been set to 512,but there were some errors:
root@6ddf679dd88b:/examples# python onnx2rknn.py
W __init__: rknn-toolkit2 version: 1.6.0+81f21f4d
W config: Please make sure the model can be dynamic when enable 'config.dynamic_input'!
W config: The 'dynamic_input' function has been enabled, the MaxShape is dynamic_input[0] = [[1, 3, 512, 512]]!
          The following functions are subject to the MaxShape:
            1. The quantified dataset needs to be configured according to MaxShape
            2. The eval_perf or eval_memory return the results of MaxShape
--> Loading model
W load_onnx: It is recommended onnx opset 19, but your onnx model opset is 17!
W load_onnx: Model converted from pytorch, 'opset_version' should be set 19 in torch.onnx.export for successful convert!
Loading : 100%|████████████████████████████████████████████████| 125/125 [00:00<00:00, 94228.61it/s]
done
--> Building model
E build: The input 0 of NonZero('/NonZero') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove NonZero('/NonZero') manually and try again!
W build: ===================== WARN(5) =====================
E rknn-toolkit2 version: 1.6.0+81f21f4d
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1971, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 779, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/graph_optimizer.py", line 347, in rknn.api.graph_optimizer._dynamic_check
E build:   File "rknn/api/rknn_log.py", line 92, in rknn.api.rknn_log.RKNNLog.e
E build: ValueError: The input 0 of NonZero('/NonZero') need to be constant! It will cause the graph to be a dynamic graph!
E build:                   Remove NonZero('/NonZero') manually and try again!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://console.zbox.filez.com/l/I00fc3 (Pwd: rknn)  Path: RKNPU2_SDK / 1.X.X / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
build model failed.

**Comment by napalm00** [comment]
@ouxiand were you able to solve this? if so, how?

**Comment by ouxiand** [comment]
Cannot use NPU model, can only use CPU, slow speed, currently no better solution.

**Comment by JohnConnor123** [comment]
Same problem with simple model from torchhub model zoo

**Comment by tomatosliu** [comment]
anyone found the solution?

**Comment by JohnConnor123** [comment]
> anyone found the solution?

You should write NonZero operation realization. There is a description in docs how to do this

**Comment by tomatosliu** [comment]
> > anyone found the solution?
> 
> You should write an implementation of the NonZero operation. The documentation contains a description of how to do this.

which documentation you refered to, could you please provide it?

**Comment by BaaBaaGoat** [comment]
there are tons of if/else in superpoint postprocess(works after convolutions),which is not supported by rockchip.just split the superpoint,let npu do convs,others for cpu.
btw i'm still stuck on lightglue:model conversion success,but fail when running:
E RKNN: [05:30:40.340] Unsupport CPU op: Einsum in this librknnrt.so,

**Comment by BaaBaaGoat** [comment]
import os
import urllib
import traceback
import time
import sys
import numpy as np
import cv2,torch
from rknn.api import RKNN
def normalize_keypoints(kpts, size):
    shift = size / 2
    scale = size.max(-1) / 2
    kpts = (kpts - shift[..., None, :]) / scale[..., None, None]
    return kpts
def superpoint_postproc(outputs):
    scores,descriptors = outputs
    scores = torch.tensor(scores)
    descriptors = torch.tensor(descriptors)
    def simple_nms(scores, nms_radius: int):
        """Fast Non-maximum suppression to remove nearby points"""
        assert nms_radius >= 0

        def max_pool(x):
            return torch.nn.functional.max_pool2d(
                x, kernel_size=nms_radius * 2 + 1, stride=1, padding=nms_radius
            )

        zeros = torch.zeros_like(scores)
        max_mask = scores == max_pool(scores)
        for _ in range(2):
            supp_mask = max_pool(max_mask.float()) > 0
            supp_scores = torch.where(supp_mask, zeros, scores)
            new_max_mask = supp_scores == max_pool(supp_scores)
            max_mask = max_mask | (new_max_mask & (~supp_mask))
        return torch.where(max_mask, scores, zeros)
    def top_k_keypoints(keypoints, scores, k):
        if k >= len(keypoints):
            return keypoints, scores
        scores, indices = torch.topk(scores, k, dim=0, sorted=True)
        return keypoints[indices], scores
    def sample_descriptors(keypoints, descriptors, s: int = 8):
        """Interpolate descriptors at keypoint locations"""
        b, c, h, w = descriptors.shape
        keypoints = keypoints - s / 2 + 0.5
        keypoints /= torch.tensor(
            [(w * s - s / 2 - 0.5), (h * s - s / 2 - 0.5)],
        ).to(
            keypoints
        )[None]
        keypoints = keypoints * 2 - 1  # normalize to (-1, 1)
        args = {"align_corners": True} if torch.__version__ >= "1.3" else {}
        descriptors = torch.nn.functional.grid_sample(
            descriptors, keypoints.view(b, 1, -1, 2), mode="bilinear", **args
        )
        descriptors = torch.nn.functional.normalize(
            descriptors.reshape(b, c, -1), p=2, dim=1
        )
        return descriptors
    nms_radius = 4
    remove_borders = 4
    detection_threshold = 0.0005
    max_num_keypoints = 2048
    scores = torch.nn.functional.softmax(scores, 1)[:, :-1]
    b, _, h, w = scores.shape
    scores = scores.permute(0, 2, 3, 1).reshape(b, h, w, 8, 8)
    scores = scores.permute(0, 1, 3, 2, 4).reshape(b, h * 8, w * 8)
    scores = simple_nms(scores, nms_radius)

    # Discard keypoints near the image borders
    if remove_borders:
        pad = remove_borders
        scores[:, :pad] = -1
        scores[:, :, :pad] = -1
        scores[:, -pad:] = -1
        scores[:, :, -pad:] = -1

    # Extract keypoints
    best_kp = torch.where(scores > detection_threshold)
    scores = scores[best_kp]

    # Separate into batches
    keypoints = [
        torch.stack(best_kp[1:3], dim=-1)[best_kp[0] == i] for i in range(b)
    ]
    scores = [scores[best_kp[0] == i] for i in range(b)]

    # Keep the k keypoints with highest score
    if max_num_keypoints is not None:
        keypoints, scores = list(
            zip(
                *[
                    top_k_keypoints(k, s, max_num_keypoints)
                    for k, s in zip(keypoints, scores)
                ]
            )
        )

    # Convert (h, w) to (x, y)
    keypoints = [torch.flip(k, [1]).float() for k in keypoints]

    descriptors = torch.nn.functional.normalize(descriptors, p=2, dim=1)

    # Extract descriptors
    descriptors = [
        sample_descriptors(k[None], d[None], 8)[0]
        for k, d in zip(keypoints, descriptors)
    ]

    resu = (torch.stack(keypoints, 0).numpy(),torch.stack(scores, 0).numpy(),torch.stack(descriptors, 0).transpose(-1, -2).contiguous().numpy())
    return resu
rknn = RKNN(verbose=True)
rknn.load_rknn("modified_superpoint.rknn")
rknn.init_runtime(target="rk3566")
data1=cv2.imread("1.png")
data2=cv2.imread("2.png")
data1=cv2.cvtColor(data1,cv2.COLOR_BGR2GRAY)[None,None,...].astype(np.float32)/255.0
data2=cv2.cvtColor(data2,cv2.COLOR_BGR2GRAY)[None,None,...].astype(np.float32)/255.0

keypoints1,scores1,descriptors1 = superpoint_postproc(rknn.inference(inputs=[data1], data_format=['nchw']))
keypoints2,scores2,descriptors2 = superpoint_postproc(rknn.inference(inputs=[data2], data_format=['nchw']))
[modified_superpoint.zip](https://github.com/user-attachments/files/17970407/modified_superpoint.zip)


that works in latest rknn-toolkit docker.

**Comment by BaaBaaGoat** [comment]
```python


# %%
import os
import urllib
import traceback
import time
import sys
import numpy as np
import cv2,torch
from rknn.api import RKNN
def normalize_keypoints(kpts, size):
    shift = size / 2
    scale = size.max(-1) / 2
    kpts = (kpts - shift[..., None, :]) / scale[..., None, None]
    return kpts
def superpoint_postproc(outputs):
    scores,descriptors = outputs
    scores = torch.tensor(scores)
    descriptors = torch.tensor(descriptors)
    def simple_nms(scores, nms_radius: int):
        """Fast Non-maximum suppression to remove nearby points"""
        assert nms_radius >= 0

        def max_pool(x):
            return torch.nn.functional.max_pool2d(
                x, kernel_size=nms_radius * 2 + 1, stride=1, padding=nms_radius
            )

        zeros = torch.zeros_like(scores)
        max_mask = scores == max_pool(scores)
        for _ in range(2):
            supp_mask = max_pool(max_mask.float()) > 0
            supp_scores = torch.where(supp_mask, zeros, scores)
            new_max_mask = supp_scores == max_pool(supp_scores)
            max_mask = max_mask | (new_max_mask & (~supp_mask))
        return torch.where(max_mask, scores, zeros)
    def top_k_keypoints(keypoints, scores, k):
        if k >= len(keypoints):
            return keypoints, scores
        scores, indices = torch.topk(scores, k, dim=0, sorted=True)
        return keypoints[indices], scores
    def sample_descriptors(keypoints, descriptors, s: int = 8):
        """Interpolate descriptors at keypoint locations"""
        b, c, h, w = descriptors.shape
        keypoints = keypoints - s / 2 + 0.5
        keypoints /= torch.tensor(
            [(w * s - s / 2 - 0.5), (h * s - s / 2 - 0.5)],
        ).to(
            keypoints
        )[None]
        keypoints = keypoints * 2 - 1  # normalize to (-1, 1)
        args = {"align_corners": True} if torch.__version__ >= "1.3" else {}
        descriptors = torch.nn.functional.grid_sample(
            descriptors, keypoints.view(b, 1, -1, 2), mode="bilinear", **args
        )
        descriptors = torch.nn.functional.normalize(
            descriptors.reshape(b, c, -1), p=2, dim=1
        )
        return descriptors
    nms_radius = 4
    remove_borders = 4
    detection_threshold = 0.0005
    max_num_keypoints = 2048
    scores = torch.nn.functional.softmax(scores, 1)[:, :-1]
    b, _, h, w = scores.shape
    scores = scores.permute(0, 2, 3, 1).reshape(b, h, w, 8, 8)
    scores = scores.permute(0, 1, 3, 2, 4).reshape(b, h * 8, w * 8)
    scores = simple_nms(scores, nms_radius)

    # Discard keypoints near the image borders
    if remove_borders:
        pad = remove_borders
        scores[:, :pad] = -1
        scores[:, :, :pad] = -1
        scores[:, -pad:] = -1
        scores[:, :, -pad:] = -1

    # Extract keypoints
    best_kp = torch.where(scores > detection_threshold)
    scores = scores[best_kp]

    # Separate into batches
    keypoints = [
        torch.stack(best_kp[1:3], dim=-1)[best_kp[0] == i] for i in range(b)
    ]
    scores = [scores[best_kp[0] == i] for i in range(b)]

    # Keep the k keypoints with highest score
    if max_num_keypoints is not None:
        keypoints, scores = list(
            zip(
                *[
                    top_k_keypoints(k, s, max_num_keypoints)
                    for k, s in zip(keypoints, scores)
                ]
            )
        )

    # Convert (h, w) to (x, y)
    keypoints = [torch.flip(k, [1]).float() for k in keypoints]

    descriptors = torch.nn.functional.normalize(descriptors, p=2, dim=1)

    # Extract descriptors
    descriptors = [
        sample_descriptors(k[None], d[None], 8)[0]
        for k, d in zip(keypoints, descriptors)
    ]

    resu = (torch.stack(keypoints, 0).numpy(),torch.stack(scores, 0).numpy(),torch.stack(descriptors, 0).transpose(-1, -2).contiguous().numpy())
    return resu

# 编译神经网络
# rknn = RKNN(verbose=True)
# rknn.config(target_platform='rk3566',dynamic_input=[
#     [[1,2048,2],[1,2048,2],[1,2048,256],[1,2048,256]],
#     [[1,512,2],[1,512,2],[1,512,256],[1,512,256]],
# ])
# rknn.load_onnx(model='onnx/superpoint_lightglue.onnx')
# rknn.build(do_quantization=False)
# rknn.export_rknn('superpoint_lightglue.rknn')


# rknn = RKNN(verbose=True)
# rknn.config(target_platform='rk3566',dynamic_input=[
#     [[1,1,720,1280]],
#     [[1,1,480,640]],
#     [[1,1,512,960]],
# ])
# rknn.load_onnx(model='onnx/modified_superpoint.onnx')
# rknn.build(do_quantization=False)
# rknn.export_rknn('modified_superpoint.rknn')

# 推理测试
rknn = RKNN(verbose=True)
rknn.load_rknn("modified_superpoint.rknn")
rknn.init_runtime(target="rk3566")
data1=cv2.imread("1.png")
data2=cv2.imread("2.png")
data1=cv2.cvtColor(data1,cv2.COLOR_BGR2GRAY)[None,None,...].astype(np.float32)/255.0
data2=cv2.cvtColor(data2,cv2.COLOR_BGR2GRAY)[None,None,...].astype(np.float32)/255.0

keypoints1,scores1,descriptors1 = superpoint_postproc(rknn.inference(inputs=[data1], data_format=['nchw']))
keypoints2,scores2,descriptors2 = superpoint_postproc(rknn.inference(inputs=[data2], data_format=['nchw']))

rknn = RKNN(verbose=True)
rknn.load_rknn("superpoint_lightglue.rknn")
rknn.init_runtime(target="rk3566")

matches0,_,mscores0,_ = rknn.inference(inputs=[
    normalize_keypoints(keypoints1,np.array(data1.shape[2:])).astype(np.float32),
    normalize_keypoints(keypoints2,np.array(data2.shape[2:])).astype(np.float32),
    descriptors1,
    descriptors2,
])
print(matches0,mscores0)
```
[modified_superpoint.zip](https://github.com/user-attachments/files/17970417/modified_superpoint.zip)
that works in latest rknn-toolkit docker.

**Comment by BaranYucecengiz** [comment]
nonzero layer implementation not enough. There are lots of layers which are not supported by rknntoolkit2. I also dont know how to write implementation. Documentation is too poor.

**Comment by bySaf** [comment]
> > nonzero layer implementation not enough. There are lots of layers which are not supported by rknntoolkit2. I also dont know how to write implementation. Documentation is too poor.
> 
> Hello, thx for your comment! Could you pls suggest what neural network converted to RKNN can we use instead LightGlue for feature extraction/matching? Thanks!

https://github.com/newcloud123/lightglue_rknn. maybe it will work
