### ISSUE TITLE
False Positive Keypoints on uniform Images

### ISSUE THREAD

**Issue by DavideCatto** [fabio-sim/LightGlue-ONNX#76]
Hello to everyone and ty for your work.
I'm extracting keypoints on uniform color images and these are the results. I have also tried to apply some gaussian blur but nothing change. How resolve this problem?

**Input Image**
![test](https://github.com/cvg/LightGlue/assets/20124934/56e6cf07-a5c4-4e56-84f3-9b48d99befd7)

**Output Keypoints draw on Input Image**
![kpts](https://github.com/cvg/LightGlue/assets/20124934/72f173e4-19ff-4887-87f2-d168c260bdea)

**Comment by fabio-sim** [comment]
Hi @DavideCatto, thank you for your interest in LightGlue-ONNX.

I don't think the extractors were trained to detect keypoints/features on uniform colour images (though in the first place, how can one obtain meaningful representations from something uniform?), so the result is the random keypoints you're getting.

**Comment by DavideCatto** [comment]
Hi @fabio-sim, yeah you're right, my question was about how to avoid to have results when you pass an uniform color image to the network. I think it was trained only on images with keypoints so when I pass an image outside the distribution of train images to the model, random keypoints are extracted. Putting a threshold on disk's keypoints not seem to resolve the problem. I have also check the orginal implementation but same results.
I think the only solution is to train disk model with also images with no keypoints.

**Comment by fabio-sim** [comment]
I agree. You would have to train the extractor to explicitly ignore uniform images.
