### ISSUE TITLE
Key points from thesuperpoint

### ISSUE THREAD

**Issue by l333wang** [fabio-sim/LightGlue-ONNX#81]
Hello, I got question about the superpoint model. The original model can return subpixel level key points coordinates in float. But here returns pixel level coordinates. Do you know where should I change to keep this in subpixel level?

**Comment by fabio-sim** [comment]
Hi @l333wang, thank you for your interest in LightGlue-ONNX.

Sorry, I don't know about that. To my knowledge, the model architecture takes an image $$(1, H, W)$$, runs it through conv layers to get features $$(64, H // 8, W// 8)$$, and reshapes it back to $$(H, W)$$ to obtain the scores matrix.

**Comment by fabio-sim** [comment]
https://github.com/kimsinjeong/keypt2subpx just released a couple of days ago, maybe it's relevant to your use case.

**Comment by l333wang** [comment]
Thanks so much
