### ISSUE TITLE
Could you tell me your versions of tensorrt and cuDNN? I encountered compatibility issues, thank you

### ISSUE THREAD

**Issue by XL634663985** [fabio-sim/LightGlue-ONNX#96]

**Comment by fabio-sim** [comment]
Hi @XL634663985, thank you for your interest in LightGlue-ONNX.

The framework versions I used to test [these models](https://github.com/fabio-sim/LightGlue-ONNX/releases/tag/v2.0) are `onnxruntime-gpu==1.18.1, CUDA 12.1, cuDNN 9.2.1, TensorRT 10.2.0.post1`, as stated [here](https://fabio-sim.github.io/blog/accelerating-lightglue-inference-onnx-runtime-tensorrt/#performance-results).

**Comment by XL634663985** [comment]
Thank you very much for your answer! I solved the problem, but in other identical versions, onnxruntime must be upgraded to the latest version (1.20.0) to run properly. I believe this is an issue with onnxruntime itself (I have tested it on two different computers). Others encountering the same problem can refer to this.
